### PR TITLE
Add internal case studies

### PR DESCRIPTION
**Pull request by hdJerry**
AC:
- [x] Create a new heading in the case studies page called "Case Studies" and rename the existing one to "External case studies"
- [x] Add a sub-heading to both that make sense (just some text, nothing crazY)
- [x] Create a method that allow us to generate a list equal to the "external case studies" but for the internal one using the available "md" file within the case studies page (covered in a another ticket)

More context:
- If we have 2 case studies in case studies folder the case studies page will show the first list with 2 cards (including our case studies) and another section with the external case studies

Screenshot 2022-09-21 at 10 05 15
Blockchain-Developer-Hub (1)
Blockchain-Developer-Hub (2)

### CODE REVIEW

**Comment by Zelig880** [comment]
Trying re-deployment

**Comment by Zelig880** [comment]
@hdJerry new comments for you:

New changes:
- [ ] change title of Nusic to "Protecting Artist's Intelectual Property"
- [ ] Change description to: "Nusic is helping musicians secure their intelectual property and their fans to invest in their favorite artists by building catalogs of NFT digital music."
- [ ] new title for Truflkatioun to be "Unbiased Economic Data"
- [ ] New description to be "Independent censorship resistant financial and economic data on-chain."
- [ ] Change Trusflation to be: Attached image
- [ ] Change image of nusic to be the one attached
- [ ] If possible also set this two image as the headers of the blogs
- [ ] 
image
- [ ] Merge the two case studies Internal and external in the same list. ust make sure internal comes first in the list



image

**Comment by hdJerry** [comment]
New changes:
- [x] change title of Nusic to "Protecting Artist's Intelectual Property"
- [x] Change description to: "Nusic is helping musicians secure their intelectual property and their fans to invest in their favorite artists by building catalogs of NFT digital music."
- [x] new title for Truflkatioun to be "Unbiased Economic Data"
- [x] New description to be "Independent censorship resistant financial and economic data on-chain."
- [x] Change Trusflation to be: Attached image
- [x] Change image of nusic to be the one attached
- [x] If possible also set this two image as the headers of the blogs
- [x] Merge the two case studies Internal and external in the same list. just make sure internal comes first in the list

@Zelig880 all changes made!

**Comment by Zelig880** [comment]
One more point (sorry I forgot):
- [ ] Move "Case studies" before "build" in the navbar
- [ ] Make sure that all the bottom navigation of the page before and after the case studies work properly

**Comment by Zelig880** [comment]
@danielgruesso All completed for you.

**Review by danielgruesso — APPROVED** [review]
LGTM, thank you

**Pull request merged**
